//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserReservationServiceReference
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://interfaces/", ConfigurationName="UserReservationServiceReference.UserReservationService")]
    public interface UserReservationService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://interfaces/UserReservationService/GetReservationConfirmationRequest", ReplyAction="http://interfaces/UserReservationService/GetReservationConfirmationResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<UserReservationServiceReference.GetReservationConfirmationResponse> GetReservationConfirmationAsync(UserReservationServiceReference.GetReservationConfirmationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://interfaces/UserReservationService/GetUserReservationsByUserIdRequest", ReplyAction="http://interfaces/UserReservationService/GetUserReservationsByUserIdResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<UserReservationServiceReference.GetUserReservationsByUserIdResponse> GetUserReservationsByUserIdAsync(UserReservationServiceReference.GetUserReservationsByUserIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://interfaces/UserReservationService/AddUserReservationRequest", ReplyAction="http://interfaces/UserReservationService/AddUserReservationResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<int> AddUserReservationAsync(UserReservationServiceReference.addUserReservationRequest arg0);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://interfaces/UserReservationService/GetUserReservationsByFlightIdRequest", ReplyAction="http://interfaces/UserReservationService/GetUserReservationsByFlightIdResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<UserReservationServiceReference.GetUserReservationsByFlightIdResponse> GetUserReservationsByFlightIdAsync(UserReservationServiceReference.GetUserReservationsByFlightIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://interfaces/UserReservationService/GetUserReservationsRequest", ReplyAction="http://interfaces/UserReservationService/GetUserReservationsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<UserReservationServiceReference.GetUserReservationsResponse> GetUserReservationsAsync(UserReservationServiceReference.GetUserReservationsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetReservationConfirmation", WrapperNamespace="http://interfaces/", IsWrapped=true)]
    public partial class GetReservationConfirmationRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int arg0;
        
        public GetReservationConfirmationRequest()
        {
        }
        
        public GetReservationConfirmationRequest(int arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetReservationConfirmationResponse", WrapperNamespace="http://interfaces/", IsWrapped=true)]
    public partial class GetReservationConfirmationResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] @return;
        
        public GetReservationConfirmationResponse()
        {
        }
        
        public GetReservationConfirmationResponse(byte[] @return)
        {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://interfaces/")]
    public partial class getUserReservationRequest
    {
        
        private int userIdField;
        
        private int flightIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int userId
        {
            get
            {
                return this.userIdField;
            }
            set
            {
                this.userIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int flightId
        {
            get
            {
                return this.flightIdField;
            }
            set
            {
                this.flightIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://interfaces/")]
    public partial class addUserReservationRequest
    {
        
        private int userIdField;
        
        private int flightIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int userId
        {
            get
            {
                return this.userIdField;
            }
            set
            {
                this.userIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int flightId
        {
            get
            {
                return this.flightIdField;
            }
            set
            {
                this.flightIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://interfaces/")]
    public partial class userTickets
    {
        
        private int idField;
        
        private double priceField;
        
        private int seatNumberField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        private userReservations userReservationsField;
        
        private flight flightField;
        
        private airport airportField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public double Price
        {
            get
            {
                return this.priceField;
            }
            set
            {
                this.priceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int SeatNumber
        {
            get
            {
                return this.seatNumberField;
            }
            set
            {
                this.seatNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string FirstName
        {
            get
            {
                return this.firstNameField;
            }
            set
            {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string LastName
        {
            get
            {
                return this.lastNameField;
            }
            set
            {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public userReservations UserReservations
        {
            get
            {
                return this.userReservationsField;
            }
            set
            {
                this.userReservationsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public flight Flight
        {
            get
            {
                return this.flightField;
            }
            set
            {
                this.flightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public airport Airport
        {
            get
            {
                return this.airportField;
            }
            set
            {
                this.airportField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://interfaces/")]
    public partial class userReservations
    {
        
        private int idField;
        
        private user userField;
        
        private flight flightField;
        
        private userTickets[] ticketsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public user User
        {
            get
            {
                return this.userField;
            }
            set
            {
                this.userField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public flight Flight
        {
            get
            {
                return this.flightField;
            }
            set
            {
                this.flightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Tickets", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public userTickets[] Tickets
        {
            get
            {
                return this.ticketsField;
            }
            set
            {
                this.ticketsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://interfaces/")]
    public partial class user
    {
        
        private int idField;
        
        private string usernameField;
        
        private string emailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Username
        {
            get
            {
                return this.usernameField;
            }
            set
            {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://interfaces/")]
    public partial class flight
    {
        
        private int idField;
        
        private airport arrivalField;
        
        private airport destinationField;
        
        private plane planeField;
        
        private System.DateTime flightDateField;
        
        private bool flightDateFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public airport Arrival
        {
            get
            {
                return this.arrivalField;
            }
            set
            {
                this.arrivalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public airport Destination
        {
            get
            {
                return this.destinationField;
            }
            set
            {
                this.destinationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public plane Plane
        {
            get
            {
                return this.planeField;
            }
            set
            {
                this.planeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public System.DateTime FlightDate
        {
            get
            {
                return this.flightDateField;
            }
            set
            {
                this.flightDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FlightDateSpecified
        {
            get
            {
                return this.flightDateFieldSpecified;
            }
            set
            {
                this.flightDateFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://interfaces/")]
    public partial class airport
    {
        
        private int idField;
        
        private string nameField;
        
        private string cityField;
        
        private string countryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string City
        {
            get
            {
                return this.cityField;
            }
            set
            {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Country
        {
            get
            {
                return this.countryField;
            }
            set
            {
                this.countryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://interfaces/")]
    public partial class plane
    {
        
        private int idField;
        
        private string typeField;
        
        private int seatsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int Seats
        {
            get
            {
                return this.seatsField;
            }
            set
            {
                this.seatsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetUserReservationsByUserId", WrapperNamespace="http://interfaces/", IsWrapped=true)]
    public partial class GetUserReservationsByUserIdRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public UserReservationServiceReference.getUserReservationRequest arg0;
        
        public GetUserReservationsByUserIdRequest()
        {
        }
        
        public GetUserReservationsByUserIdRequest(UserReservationServiceReference.getUserReservationRequest arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetUserReservationsByUserIdResponse", WrapperNamespace="http://interfaces/", IsWrapped=true)]
    public partial class GetUserReservationsByUserIdResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute()]
        [System.Xml.Serialization.XmlArrayItemAttribute("reservations", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public UserReservationServiceReference.userReservations[] @return;
        
        public GetUserReservationsByUserIdResponse()
        {
        }
        
        public GetUserReservationsByUserIdResponse(UserReservationServiceReference.userReservations[] @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetUserReservationsByFlightId", WrapperNamespace="http://interfaces/", IsWrapped=true)]
    public partial class GetUserReservationsByFlightIdRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public UserReservationServiceReference.getUserReservationRequest arg0;
        
        public GetUserReservationsByFlightIdRequest()
        {
        }
        
        public GetUserReservationsByFlightIdRequest(UserReservationServiceReference.getUserReservationRequest arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetUserReservationsByFlightIdResponse", WrapperNamespace="http://interfaces/", IsWrapped=true)]
    public partial class GetUserReservationsByFlightIdResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute()]
        [System.Xml.Serialization.XmlArrayItemAttribute("reservations", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public UserReservationServiceReference.userReservations[] @return;
        
        public GetUserReservationsByFlightIdResponse()
        {
        }
        
        public GetUserReservationsByFlightIdResponse(UserReservationServiceReference.userReservations[] @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetUserReservations", WrapperNamespace="http://interfaces/", IsWrapped=true)]
    public partial class GetUserReservationsRequest
    {
        
        public GetUserReservationsRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetUserReservationsResponse", WrapperNamespace="http://interfaces/", IsWrapped=true)]
    public partial class GetUserReservationsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute()]
        [System.Xml.Serialization.XmlArrayItemAttribute("reservations", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public UserReservationServiceReference.userReservations[] @return;
        
        public GetUserReservationsResponse()
        {
        }
        
        public GetUserReservationsResponse(UserReservationServiceReference.userReservations[] @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface UserReservationServiceChannel : UserReservationServiceReference.UserReservationService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class UserReservationServiceClient : System.ServiceModel.ClientBase<UserReservationServiceReference.UserReservationService>, UserReservationServiceReference.UserReservationService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public UserReservationServiceClient() : 
                base(UserReservationServiceClient.GetDefaultBinding(), UserReservationServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.UserReservationServiceImplPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public UserReservationServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(UserReservationServiceClient.GetBindingForEndpoint(endpointConfiguration), UserReservationServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public UserReservationServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(UserReservationServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public UserReservationServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(UserReservationServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public UserReservationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UserReservationServiceReference.GetReservationConfirmationResponse> UserReservationServiceReference.UserReservationService.GetReservationConfirmationAsync(UserReservationServiceReference.GetReservationConfirmationRequest request)
        {
            return base.Channel.GetReservationConfirmationAsync(request);
        }
        
        public System.Threading.Tasks.Task<UserReservationServiceReference.GetReservationConfirmationResponse> GetReservationConfirmationAsync(int arg0)
        {
            UserReservationServiceReference.GetReservationConfirmationRequest inValue = new UserReservationServiceReference.GetReservationConfirmationRequest();
            inValue.arg0 = arg0;
            return ((UserReservationServiceReference.UserReservationService)(this)).GetReservationConfirmationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UserReservationServiceReference.GetUserReservationsByUserIdResponse> UserReservationServiceReference.UserReservationService.GetUserReservationsByUserIdAsync(UserReservationServiceReference.GetUserReservationsByUserIdRequest request)
        {
            return base.Channel.GetUserReservationsByUserIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<UserReservationServiceReference.GetUserReservationsByUserIdResponse> GetUserReservationsByUserIdAsync(UserReservationServiceReference.getUserReservationRequest arg0)
        {
            UserReservationServiceReference.GetUserReservationsByUserIdRequest inValue = new UserReservationServiceReference.GetUserReservationsByUserIdRequest();
            inValue.arg0 = arg0;
            return ((UserReservationServiceReference.UserReservationService)(this)).GetUserReservationsByUserIdAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<int> AddUserReservationAsync(UserReservationServiceReference.addUserReservationRequest arg0)
        {
            return base.Channel.AddUserReservationAsync(arg0);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UserReservationServiceReference.GetUserReservationsByFlightIdResponse> UserReservationServiceReference.UserReservationService.GetUserReservationsByFlightIdAsync(UserReservationServiceReference.GetUserReservationsByFlightIdRequest request)
        {
            return base.Channel.GetUserReservationsByFlightIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<UserReservationServiceReference.GetUserReservationsByFlightIdResponse> GetUserReservationsByFlightIdAsync(UserReservationServiceReference.getUserReservationRequest arg0)
        {
            UserReservationServiceReference.GetUserReservationsByFlightIdRequest inValue = new UserReservationServiceReference.GetUserReservationsByFlightIdRequest();
            inValue.arg0 = arg0;
            return ((UserReservationServiceReference.UserReservationService)(this)).GetUserReservationsByFlightIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UserReservationServiceReference.GetUserReservationsResponse> UserReservationServiceReference.UserReservationService.GetUserReservationsAsync(UserReservationServiceReference.GetUserReservationsRequest request)
        {
            return base.Channel.GetUserReservationsAsync(request);
        }
        
        public System.Threading.Tasks.Task<UserReservationServiceReference.GetUserReservationsResponse> GetUserReservationsAsync()
        {
            UserReservationServiceReference.GetUserReservationsRequest inValue = new UserReservationServiceReference.GetUserReservationsRequest();
            return ((UserReservationServiceReference.UserReservationService)(this)).GetUserReservationsAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.UserReservationServiceImplPort))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.MtomMessageEncodingBindingElement mtomBindingElement = new System.ServiceModel.Channels.MtomMessageEncodingBindingElement();
                mtomBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(mtomBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.UserReservationServiceImplPort))
            {
                return new System.ServiceModel.EndpointAddress("http://desktop-ve5gok9:8080/ProjectServer-1.0-SNAPSHOT/UserReservationServiceImpl" +
                        "Service");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return UserReservationServiceClient.GetBindingForEndpoint(EndpointConfiguration.UserReservationServiceImplPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return UserReservationServiceClient.GetEndpointAddress(EndpointConfiguration.UserReservationServiceImplPort);
        }
        
        public enum EndpointConfiguration
        {
            
            UserReservationServiceImplPort,
        }
    }
}
